/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2022-04-25 04:12:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	if(request.getServerName().toLowerCase().indexOf("admin") > -1 || request.getServerName().toLowerCase().indexOf("app") > -1 ){
		return;
	}else if(request.getServerName().toLowerCase().indexOf("dev") == -1){
		String userAgent = request.getHeader("User-Agent").toLowerCase();
		if(userAgent.indexOf("android") > -1 || userAgent.indexOf("iphone") > -1 || userAgent.indexOf("ipad") > -1 || request.getServerName().toLowerCase().indexOf("m.askavatar") > -1 || request.getServerName().toLowerCase().indexOf("www.askavatar") > -1){
			// response.sendRedirect("https://m.askavatar.ai/home_0002_01.act");
			response.sendRedirect("http://localhost:8080/home_0002_01.act");
		}else{
			// response.sendRedirect("https://askavatar.ai/home_0001.act");	// 공인인증서 복사 페이지
			//response.sendRedirect("https://m.askavatar.ai/home_0002_01.act");
			response.sendRedirect("http://localhost:8080/home_0002_01.act");
		}
		return;
	}else if(request.getRemoteAddr().indexOf("10.254.24") == -1){
		// 다큐브 여의도 본사 IP 허용
		if(request.getRemoteAddr().indexOf("121.131.131") == -1){
			return;
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\">\r\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("\t<title></title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.container { padding-right:15px;}\r\n");
      out.write("\thtml, body, div, ul {margin:0;padding:0;border:0;outline:0;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;}\r\n");
      out.write("\tul, ol, dl {list-style:none;}\r\n");
      out.write("\t.list li {margin:5px;padding:5px;position:relative; width:98%; margin-top:12px; background:#fff; border-radius:5px; box-shadow:0 2px 0 0 rgba(0,0,0,.05);}\r\n");
      out.write("\t.list li.b {margin:5px;padding:5px;background-color:#99d7f5;}\r\n");
      out.write("\t.list li.w {margin:5px;padding:5px;background-color:#fff;}\r\n");
      out.write("\t.list li.o {margin:5px;padding:5px;background-color:#f5d099;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("<div class=\"grey_area container\">\r\n");
      out.write("<div style=\"padding:7px;\">개발 테스트</div>\r\n");
      out.write("<div>\r\n");
      out.write("<ul class=\"list\">\r\n");
      out.write("\t<li class=\"b\"><a href=\"/test_0002_01.act\">PUSH SEND</a></li>\r\n");
      out.write("\t<li class=\"b\"><a href=\"/test/publ_main.jsp\">퍼블확인</a></li>\r\n");
      out.write("\t<li class=\"b\"><a href=\"test_0001_01.act\">테스트목록조회 </a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"/gw/auth.jsp\">로그인 (test)</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"/gw/auth.jsp?USE_INTT_ID=A039900001\">로그인 (A039900001)</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"/gw/auth.jsp?USE_INTT_ID=A210100001\">로그인 (A210100001)</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"/gw/auth.jsp?USE_INTT_ID=A211000006\">로그인 (A211000006)</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"/gw/auth.jsp?USE_INTT_ID=A200300026&LGIN_APP=AVATAR\">로그인 (A200300026)</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"/gw/auth.jsp?USE_INTT_ID=A211000008&LGIN_APP=AVATAR\">로그인 (A211000008)</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"join_0001_01.act\">회원가입</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"ques_0001_01.act\">질의</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"basic_0003_01.act\">데이터</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"basic_0001_01.act\">더보기</a></li>\r\n");
      out.write("\t<li class=\"w\"><a href=\"home_0001.act\">인증서 복사</a></li>\r\n");
      out.write("\t<!-- admin포탈에 등록 -->\r\n");
      out.write("\t<li class=\"o\"><a href=\"/gw/weauth.jsp?CNTS_IDNT_ID=AVATAR_CSTM&RDM_KEY=test\" target=\"_blank\">어드민 (AVATAR 고객관리)</a></li>\r\n");
      out.write("\t<li class=\"o\"><a href=\"/gw/weauth.jsp?CNTS_IDNT_ID=AVATAR_STTC&RDM_KEY=test\" target=\"_blank\">어드민 (AVATAR 통계보고서)</a></li>\r\n");
      out.write("\t<li class=\"o\"><a href=\"/gw/weauth.jsp?CNTS_IDNT_ID=AVATAR_HMPG&RDM_KEY=test\" target=\"_blank\">어드민 (AVATAR 홈페이지관리)</a></li>\r\n");
      out.write("\t<li class=\"o\"><a href=\"/gw/weauth.jsp?CNTS_IDNT_ID=AVATAR_SRVC&RDM_KEY=test\" target=\"_blank\">어드민 (AVATAR 서비스관리)</a></li>\r\n");
      out.write("\t<li class=\"o\"><a href=\"/gw/weauth.jsp?CNTS_IDNT_ID=AVATAR_SSTM&RDM_KEY=test\" target=\"_blank\">어드민 (AVATAR 시스템관리 )</a></li>\r\n");
      out.write("\t<!-- admin포탈에 등록 x -->\r\n");
      out.write("\t<li class=\"o\"><a href=\"/gw/weauth.jsp?CNTS_IDNT_ID=AVATAR_SRVC2&RDM_KEY=test\" target=\"_blank\">어드민 (질의센터)</a></li>\r\n");
      out.write("\t<li class=\"o\"><a href=\"/gw/weauth.jsp?CNTS_IDNT_ID=AVATAR_PLFM&RDM_KEY=test\" target=\"_blank\">어드민 (플랫폼회원관리)</a></li>\r\n");
      out.write("\t<li class=\"o\"><a href=\"/gw/weauth.jsp?CNTS_IDNT_ID=AVATAR_BLBD&RDM_KEY=test\" target=\"_blank\">어드민 (게시물관리)</a></li>\r\n");
      out.write("\t<li class=\"o\"><a href=\"/gw/weauth.jsp?CNTS_IDNT_ID=AVATAR_CLDC&RDM_KEY=test\" target=\"_blank\">어드민 (클라우드센터)</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
